---
# Tasks to install and start fail2ban

- name: 'fail2ban: install package'
  community.general.pkgng:
    name: "py{{ ansible_python.version.major }}{{ ansible_python.version.minor }}-fail2ban"
    state: present

- name: "fail2ban: Set fail2ban_enable YES"
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    regexp: '^\s*fail2ban_enable\s*=(.*)$'
    line: 'fail2ban_enable="YES"'

- name: 'fail2ban: create db dir'
  ansible.builtin.file:
    state: directory
    access_time: preserve
    modification_time: preserve
    path: '/var/db/fail2ban'
    owner: "{{ pf_pflog_owner }}"
    group: "{{ pf_pflog_group }}"
    mode: '0750'

- name: 'fail2ban: create persist file'
  ansible.builtin.file:
    state: touch
    access_time: preserve
    modification_time: preserve
    path: "{{ pf_fail2ban_persistfile }}"
    owner: "{{ pf_pflog_owner }}"
    group: "{{ pf_pflog_group }}"
    mode: '0644'

- name: 'fail2ban: add openvpn filter'
  ansible.builtin.copy:
    src: openvpn.local
    dest: "{{ pf_fail2ban_dir }}/filter.d/openvpn.local"
    owner: "{{ pf_pflog_owner }}"
    group: "{{ pf_pflog_group }}"
    mode: '0644'
  notify: restart fail2ban

- name: 'fail2ban: add milter-regex filter'
  ansible.builtin.copy:
    src: milter-regex.local
    dest: "{{ pf_fail2ban_dir }}/filter.d/milter-regex.local"
    owner: "{{ pf_pflog_owner }}"
    group: "{{ pf_pflog_group }}"
    mode: '0644'
  notify: restart fail2ban

- name: 'fail2ban: add bsd-pf config'
  ansible.builtin.copy:
    src: bsd-pf.conf
    dest: "{{ pf_fail2ban_dir }}/action.d/bsd-pf.conf"
    owner: "{{ pf_pflog_owner }}"
    group: "{{ pf_pflog_group }}"
    mode: '0644'
  notify: restart fail2ban

- name: 'fail2ban: add fail2ban-flushlogs script'
  ansible.builtin.copy:
    src: 'fail2ban-flushlogs'
    dest: '/usr/local/bin/fail2ban-flushlogs'
    owner: "{{ pf_pflog_owner }}"
    group: "{{ pf_pflog_group }}"
    mode: '0755'

- name: 'fail2ban: create fail2ban.local'
  ansible.builtin.template:
    dest: "{{ pf_fail2ban_dir }}/fail2ban.local"
    src: fail2ban.local.j2
    owner: "{{ pf_pflog_owner }}"
    group: "{{ pf_pflog_group }}"
    mode: '0644'
  notify: restart fail2ban

- name: 'fail2ban: create jail.local'
  ansible.builtin.template:
    dest: "{{ pf_fail2ban_dir }}/jail.local"
    src: jail.local.j2
    owner: "{{ pf_pflog_owner }}"
    group: "{{ pf_pflog_group }}"
    mode: '0644'
  notify: restart fail2ban

- name: 'fail2ban: enable jail services'
  ansible.builtin.template:
    src: service.local.j2
    dest: "{{ pf_fail2ban_dir }}/jail.d/{{ item }}.local"
    owner: "{{ pf_pflog_owner }}"
    group: "{{ pf_pflog_group }}"
    mode: '0644'
  with_items: "{{ pf_fail2ban_conf | default([]) }}"
  loop_control:
    label: "{{ item }}.local"
  notify: restart fail2ban
