---
# tasks file for coffeesprout.pf

# Generate a list of interfaces that will take thd default firewall rules
- set_fact:
    pf_default_ifs: "{{ ansible_interfaces | difference(pf_skip | default([])) | difference(pf_secure_ifs | default([])) | difference([ pf_primary_interface ]) }}"

- name: ensure pf module is loaded
  kld:
    name: pf
    boot: True

- name: ensure pf is enabled in rc.conf
  community.general.sysrc:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop: "{{ pf_rc_conf }}"
  tags:
  - services
  - configuration

- name: Install fail2ban
  include_tasks:
    file: 'fail2ban.yml'
  when: pf_fail2ban|bool
  tags:
  - fail2ban

- name: Install ipdbtools
  include_tasks:
    file: 'ipdbtools.yml'
  when: pf_ipdbtools|bool
  tags:
  - ipdb

- name: ensure pf.conf is created
  template:
    dest: /etc/pf.conf
    src: pf.conf.j2
    backup: yes
    validate: '/sbin/pfctl -nf %s'
    owner: 'root'
    group: 'network'
    mode: '640'
  notify: Reload PF
  tags:
  - configure

- name: 'pf: verify device owner/group/mode'
  ansible.builtin.file:
    state: file
    access_time: preserve
    modification_time: preserve
    path: "{{ pf_device_name }}"
    owner: "{{ pf_device_owner }}"
    group: "{{ pf_device_group }}"
    mode: "{{ pf_device_mode }}"
  tags:
  - configure
