---
# handlers file for coffeesprout.pf

- name: Reload PF
  command: /sbin/pfctl -f /etc/pf.conf

- name: enable and start fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true

- name: restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
  when:
    - pf_fail2ban | bool
    - not ansible_check_mode | bool
